### ISSUE TITLE
Open Source license

### ISSUE THREAD

**Issue by Midi-In** [petoolse/petools#11]
Why is this project being hosted on GitHub without its sources being available? Have you ever considered making it open? What is the point of hosting proprietary software on Git?

**Comment by upiter** [comment]
> Why is this project being hosted on GitHub without its sources being available?

[Midi](https://github.com/Midi-In), are you sure that you understand the purpose of GitHub?
Do you really think that the only reason to use `git` is to publish C/C++ sources?
Do you know [GitHub Pages](https://pages.github.com)?
Check it out: [petoolse.github.io/petools](https://petoolse.github.io/petools/)!
There is a branch for PE Tools web site: [gh-pages](https://github.com/petoolse/petools/tree/gh-pages), try it.

So, what the problem with the license? You don't like permissive [MIT](https://github.com/petoolse/petools/blob/master/LICENSE) license? MIT license lets you use everything in this repo. Isn't OK for you?

> What is the point of hosting proprietary software on Git?

Well, this repo contains:
- PE Tools [web site](https://petoolse.github.io/petools/) (see above)
- Issues (yeah, you just used this feature)

Do you complain every time you find a repo with only Issues and web site?

@Midi-In, if you do not enjoy PE Tools release, please find another tool to use in you practice, we don't give a f about that, really.
