### ISSUE TITLE
Calculation of entry

### ISSUE THREAD

**Issue by circutrider21** [petoolse/petools#12]
Sorry to bother, but do you have any Idea on how to calculate the entry point of a PE Executable. Since the source code is unavailable I have no idea on how petools does it and was wondering you could tell me.

**Comment by upiter** [comment]
> how to calculate the entry point of a PE Executable

GitHub search is very usable for this:
[AddressOfEntryPoint](https://github.com/search?q=AddressOfEntryPoint&type=code)

One of thousands answers:
[peconv::get_entry_point_rva](https://github.com/hasherezade/libpeconv/blob/4aa54448bea06d9f7f93b8ef79789ab85bb04272/libpeconv/src/pe_hdrs_helper.cpp#L171)
