### ISSUE TITLE
n00b-ы тожо хотят что нибудь патчить

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [petoolse/petools#14]
нужно подменить новую версию dll-ки старой
а новую версию тоже подключить но использоватть только недостающие функции
но хочетсо обойтись без писание proxy dll-ов
а знания в этой области весьма поверхностные
вто время когда гугол уже полностью бесполезен...

можно ли в таблице импорт exe-шника удалить недостающие в старой версии процедуры?
и добавить в таблицу импорта новую версию dll-ки под другим именем со списком только недостающих процедур
так чтоб при загрузке dll-ок список фактическими адресов процедур получился собранным из двух dll-ок вместо одной

хотя тыкаю petools отдельные импортируемые функции тут удалять нельзя
и добавлять их можно только вместе с добавлением целой dll-ки но не после создания
тут бы было полезно в менюшке add import иметь возможность открывать целую гготовую dll-ку 
из которой уже подтягивать список функций

кто подскажет в какую сторону копать?

**Comment by upiter** [comment]
Name one library as "lib1.dll" (legacy one) and another as "lib2.dll" (new one).

Create "forward.def" file for linker, then fill it to map functions to corresponding DLLs.

Sample syntax:


```ini
; forward.def
EXPORTS
	func1 = lib1.func1
	func2 = lib2.func2
```

Note that `func1` will be imported from **lib1** and `func2` from **lib2**.

Link DLL with dummy `DllMain` and you'll get new "forward.dll" containing forwarders to legacy (lib1.dll) and new (lib2.dll) libraries.

In case of errors at runtime:
- Check init functions of both libraries, context, memory allocation etc.
