### ISSUE TITLE
Can't dump 64-bit programs with PETools

### ISSUE THREAD

**Issue by Aholicknight** [petoolse/petools#15]
I am trying to dump a program that is 64-bit, for some reason it doesn't let me. 

I recorded a video of me trying to dump the program which can be viewed here:

https://user-images.githubusercontent.com/7843719/163918150-735c3d32-1a32-4ddd-abb6-9fb68af72962.mp4

Is there anything that I am doing wrong? I am using the latest version from GitHub + the program opens as administrator, so I have no idea what I am doing wrong. Thank you!

**Comment by upiter** [comment]
Use [OllyDumpEx](https://low-priority.appspot.com/ollydumpex/) to dump 64 bit processes.
PE Tools' dumper is obsolete and unusable.

## OllyDumpEx Features

- Various debuggers supported
- Select to dump debugee exe, loaded dll or non-listed module
- Search PE File from memory
- Multiple Dump mode. Rebuild for typical PE dump, Binary for PE Carving
- PE32+ supported (Search and Binary Dump mode only available on 32bit debugger)
- Native 64bit process supported (IDA Pro, WinDbg and x64dbg)
- ELF supported (both of 32bit and 64bit)
- Standalone version available
- Dump any address space as section even if not in original section header
- Auto calculate many parameters (RawSize, RawOffset, VirtualOffset, ...)

## OllyDumpEx screenshot
![](https://low-priority.appspot.com/ollydumpex/ollydumpex_ss2.png)

**Comment by somk** [comment]
已经收到。

**Comment by Aholicknight** [comment]
> Use [OllyDumpEx](https://low-priority.appspot.com/ollydumpex/) to dump 64 bit processes. PE Tools' dumper is obsolete and unusable.

@upiter thank you for the fast reply, do you suggest any other program like PE Tools? The only reason why I still use PE Tools is because of all the features included with it. I have OllyDumpEx but wondering if there is any alternatives like PE Tools. Thank you!

**Comment by upiter** [comment]
For PE **viewing and analysis** (not manipulation) there are many handy tools like [Detect It Easy](https://github.com/horsicq/Detect-It-Easy), but for PE **manipulation** [PE Tools](https://github.com/petoolse/petools) features are good enough.

**Comment by Aholicknight** [comment]
> For PE **viewing and analysis** (not manipulation) there are many handy tools like [Detect It Easy](https://github.com/horsicq/Detect-It-Easy), but for PE **manipulation** [PE Tools](https://github.com/petoolse/petools) features are good enough.

@upiter all right sounds good, thank you for the suggestions!
