### ISSUE TITLE
DLL Imports editing

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [petoolse/petools#16]
there is a PE tool
why i need to use hex editor to change dll name instead of directly edit it in PE tool?
![2022-04-22_171934](https://user-images.githubusercontent.com/88002487/164733018-41075f5e-2984-4293-91f8-dea4ab5166f6.png)
its editing but changes not saving

**Comment by upiter** [comment]
Long story short:
`if new dll name size` > `old dll name size` then import rebuild process is required.

**Comment by NEO-SPECTRUMAN** [comment]
yes but now it is not even possible to "same size" rename

**Comment by NEO-SPECTRUMAN** [comment]
also i wrote duplicate issue....
https://github.com/petoolse/petools/issues/8

**Comment by NEO-SPECTRUMAN** [comment]
ALSO
editing unavalable when process is runing 

the better way is to allow editng
with warning when saving with retry button

i just want patch when process is display error with function name
after prrogram closing its will be posible to save changes...

**Comment by upiter** [comment]
To edit process' memory you must dump executable first and then edit values in dumped file.
PE Tools don't support  in-memory process editing.

**Comment by NEO-SPECTRUMAN** [comment]
not process memory
runned .exe only

**Comment by NEO-SPECTRUMAN** [comment]
for example
![2022-04-24_165441](https://user-images.githubusercontent.com/88002487/164979410-ff8d29ab-7342-4ce6-844c-31392ea32cf6.png)
