### ISSUE TITLE
What the mean of the "question mark" button?

### ISSUE THREAD

**Issue by GF-Huang** [petoolse/petools#17]
![image](https://user-images.githubusercontent.com/4510984/167307529-68454242-ede1-4f15-afed-80737c738d5b.png)

**Comment by upiter** [comment]
When you press `?` button, PE Tools will try to recalculate corresponding value.
For example, recalculate image checksum in PE header.

**Comment by GF-Huang** [comment]
"?" made me think it was randomly generated.

**Comment by upiter** [comment]
Yeah, it's a little bit confusing.
