### ISSUE TITLE
Show SeDebugPrivilege warning at app start

### ISSUE THREAD

**Issue by andriyankov** [petoolse/petools#18]
Понятно, что пользовать программы достаточно умный человек. Reversing Engineering привлекает далеко не простых глупых людей, но тем неменее нужно бы решить проблему с этим warning-ом. Возможно дописать мини-инструкцию куда-либо с описанием почему оно появляется и чем грозит, если грозит, пользователю? Если ничего нельзя сделать, то пояснить как пользователю это поправить у себя в системе

![image](https://user-images.githubusercontent.com/14892028/189866745-89cdbe4b-0ea4-43dc-bd83-d056ba2f885c.png)

**Comment by somk** [comment]
已经收到。

**Comment by upiter** [comment]
[System Requirements](https://github.com/petoolse/petools#system-requirements):
- Administrative rights for `SeDebugPrivilege`

P.S. Достаточно умный человек читает README

**Comment by somk** [comment]
已经收到。
