### ISSUE TITLE
Latest Release is Infected

### ISSUE THREAD

**Issue by HorridModz** [petoolse/petools#19]
I downloaded [PE Tools v1.9.762.2018](https://github.com/petoolse/petools/releases/tag/v1.9.762), which was the latest release in this github repository, and extracted the 7z archive with WinRAR. When I tried to run it,  avast warned me that it was a PUP.  I put the exe file into virustotal, and got back bad results: 
[Virustotal Scan](https://www.virustotal.com/gui/file/8fd1a1cc1a253fd58693c181895d392ba20fc2a638aaecbc2e8f5d004db8fc27)

**Comment by somk** [comment]
已经收到。

**Comment by HorridModz** [comment]
> 已经收到。

Sorry, closing issue.

**Comment by upiter** [comment]
Duplicate of #7
