### ISSUE TITLE
Compile for linux?

### ISSUE THREAD

**Issue by b1ek** [petoolse/petools#20]
hey there,

i am working for a company that uses only linux systems. where is the source available? i'd really love to use it at work but we have to compile everything from source for security reasons

**Comment by somk** [comment]
已经收到。

**Comment by b1ek** [comment]
@somk could you reply in english, please? i dont understand what you have said

**Comment by upiter** [comment]
@b1ek
> i am working for a company that uses only linux systems.

Then use [Wine](https://wiki.winehq.org/Download).


> where is the source available?

Please read the official [README](https://github.com/petoolse/petools#source-code) carefully.
